### ISSUE TITLE
Issue with Exceptions for d.tube

### ISSUE THREAD

**Issue by Cade66** [SimonBrazell/privacy-redirect#97] opened 2020-08-28 15:09 UTC
Hi,

Running flawlessly Privacy Redirect 1.1.40 on Firefox 80.0

I have one exception which runs fine : `http://localhost/` (entered as url)
I tested a few others, no issue
I encountered though an issue with `https://d.tube/` : a video link such as `https://d.tube/#!/v/romafedorov/0sxi2w3wpl5` is redirected to my Invidious instance

No idea why. Thanks for your diagnostic (and for the extension, by the way!)

**Comment by SimonBrazell** [comment] 2020-08-28 22:46
Okay so you don't want d.tube embedded videos redirected? I'll do some testing and see what's up.

**Comment by Cade66** [comment] 2020-08-28 23:06
It's not that I don't want d.tube videos to be redirected, I don't even use d.tube myself but I do test several sites as well as their relation to extensions.
The Exceptions feature has been included in Privacy Redirect for a good reason I presume, that of being used.
If I encounter a site where a dedicated extension extension fails I report it, not for the pleasure but for the extension's sake; also, by curiosity I must say.
So if you get this issue resolved, please : don't do it for me, I'm not asking anything, only reporting!

**Comment by SimonBrazell** [comment] 2020-08-29 01:49
Oh right, good stuff! Thanks for that.

Just doing some testing on that site, it's working for me on Chromium:

Here is the exception:
<img width="392" alt="Screen Shot 2020-08-29 at 11 46 34 am" src="https://user-images.githubusercontent.com/16571951/91625772-63da6700-e9ed-11ea-835e-0985073b1a46.png">

If you look closely you'll notice that this is the YouTube player and not invidious:
![Screen Shot 2020-08-29 at 11 46 46 am](https://user-images.githubusercontent.com/16571951/91625778-6d63cf00-e9ed-11ea-85c4-d3964b580a72.png)

So perhaps the issue is specific to Firefox 80? I'll see how it goes on my install.

**Comment by SimonBrazell** [comment] 2020-08-29 01:56
Worked on Firefox Developer Edition 80.0b1 (64-bit), perhaps there is something specific about your setup then, how does the exception for that site look in your preferences?

**Comment by SimonBrazell** [comment] 2020-08-29 01:58
To be honest the site itself seems a little flakey to me, the player doesn't seem to load every time, it least on FF anyway.

**Comment by Cade66** [comment] 2020-08-29 08:28
@SimonBrazell , `To be honest the site itself seems a little flakey to me, the player doesn't seem to load every time, at least on FF anyway.`
A _little_ is maybe putting it mildly.

**1-** My Privacy Redirect Exceptions:
![PR-settings](https://user-images.githubusercontent.com/65161029/91632227-b876e580-e9df-11ea-865a-d4308b1f0725.jpg)
 

**2-** Here is what I've experienced.

YouTube embedded videos in D.tube are handled differently from one video to another.
**With the video you've tested above** (`https://d.tube/#!/v/mvd/QmaLB3VsVA3mpzS6UQa5cpb2PdqmaFKyjLR65pMjEUKQGM`) I get the same result as you : embedded YouTube is **_not_** redirected to Invidious:
![PR-video1](https://user-images.githubusercontent.com/65161029/91632272-13a8d800-e9e0-11ea-9f5b-2b25d2e1ef83.jpg)

**But with another video**, the one for instance I mentioned in my first comment (`https://d.tube/#!/v/romafedorov/0sxi2w3wpl5`) the embedded YouTube video **_is_** redirected to Invidious:
![PR-video2](https://user-images.githubusercontent.com/65161029/91632381-9762c480-e9e0-11ea-98a2-e89e7578b30f.jpg)

Now, the most amazing is this: 
the first video (yours) opens with YouTube even **_without_** the Privacy Redirect exception.
the second video (mine) opens with Invidious even **_with_** the Privacy Redirect exception.

Obviously D.tube has its very own YouTube embedded recipe and it seems this explains above related.
It's not a Privacy Redirect issue but a site's very specific handling of embedded YouTube videos.
Thanks for having investigated as well. My thread appears to be obsolete unless to consider a user's related experience as worth being expressed.
We'll carry on and avoid D.tube.

**Comment by SimonBrazell** [comment] 2020-08-31 06:37
Hi @Cade66 thanks for the investigation, I believe your conclusions are correct, perhaps there is a service worker involved here that is loading the content from a cache, so the extension doesn't get a chance to intercept the requests? I've had problems in the past with service workers doing similar stuff with Twitter. 

Anyway I'll close this for now given it appears to be site specific. Let me know if you come across anything else.

Cheers!

**Closed by SimonBrazell** 2020-08-31 06:37 UTC
