### ISSUE TITLE
Twitter without subdomain doesn't redirect to Nitter

### ISSUE THREAD

**Issue by Daedren** [SimonBrazell/privacy-redirect#5] opened 2019-12-23 12:15 UTC
If I access `https://www.twitter.com/`, the extension redirects me to Nitter without a problem.

However, if I access `https://twitter.com`, it doesn't.
The console yields the following error
```
home:1 Refused to load manifest from 'https://nitter.net/manifest.json' because it violates the following Content Security Policy directive: "manifest-src 'self'".
```

Browser info:

Vivaldi | 2.9.1705.41 (Stable channel) (64-bit)
-- | --
Revision | ce637bfd730e6b2e549bf8def38f849e1a26bd3b
OS | Windows 10 OS Version 1703 (Build 15063.2078)
JavaScript | V8 7.8.279.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.99 Safari/537.36 Vivaldi/2.9.1705.41

Let me know if you need any more info, and thank you for the great extension.

**Comment by Daedren** [comment] 2019-12-25 13:23
Can also replicate on Firefox.

Name | Firefox
-- | --
Version | 72.0b9
Build ID|20191219234059
Update Channel |aurora
User Agent |Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
OS |Windows_NT 10.0
Launcher Process|Enabled
Multiprocess Windows |2/2 Enabled by default
Remote Processes|10
Enterprise Policies|Inactive
Safe Mode|false

**Comment by SimonBrazell** [comment] 2019-12-27 00:57
Hello @Daedren sorry I've been away for the holidays, thanks for the heads up I'll look into this over the next week. Cheers!

**Comment by SimonBrazell** [comment] 2020-01-02 03:17
@Daedren I can't replicate this on Chrome or Firefox, navigating to twitter.com redirects to nitter.net as expected with no errors shown in the console. Perhaps the issue you are experiencing is due to some other problem with the browser config you are using?

**Comment by SimonBrazell** [comment] 2020-01-02 03:34
Looking at the error message you posted it looks to be caused by something in the `nitter.net` site Content Security Policy, I don't believe this issue is related to the extension. 

Have you tried it with other Nitter [instances](https://github.com/zedeus/nitter/wiki/Instances) as well?

**Comment by Daedren** [comment] 2020-01-02 16:54
> Have you tried it with other Nitter instances as well?
Yep, doesn't work either. Tried disabling all my extensions as well.

I figured it out though, I was signed into Twitter. 
nce I logged out, the redirect started working on the links without a subdomain.

**Comment by SimonBrazell** [comment] 2020-01-03 00:38
Hmm yeah that sounds about right actually, I just haven't experienced it since I never login to Twitter myself, I don't think Nitter handles this situation, I'll have a look on their repo and some other extensions though to see if there is a workaround I can use.

**Comment by SimonBrazell** [comment] 2020-01-18 00:45
Closing as this is a limitation of Nitter, not the extension. For now I'd suggest disabling Nitter redirects if you want to use Twitter account features, or logging out like you mentioned. One thing I could do is try to fix the 'Open in Twitter' feature so it works with this extension, I think to do that I'd need to maintain a list of Nitter instances and check for requests to Twitter from them and bypass the redirects if it is from those instances. I'll look into that.

**Closed by SimonBrazell** 2020-01-18 00:45 UTC

**Comment by pkillnine** [comment] 2020-07-29 19:20
I had this same issue but I wasn't logged in to Twitter. I fixed it by clearing cookies from Twitter.
