### ISSUE TITLE
[BUG] Add support for youtube embed

### ISSUE THREAD

**Issue by wuniversales** [SimonBrazell/privacy-redirect#44] opened 2020-04-30 11:59 UTC
URL of the error: https://wii.scenebeta.com/tutorial/como-instalar-cmios-en-la-wii

I have been able to verify that the type links ...
`http://www.youtube.com/v/B8uurHgZLsU&hl=es&fs=1&rel=0&color1=0x234900&color2=0x4e9e00&border=1`
They do not work
It should generate a basic url, for example...
`https://invidious.snopyta.org/embed/B8uurHgZLsU`
_PD: I am seeing that it works through object, I don't know exactly what the solution will be, but I suppose it is possible to fix it._
Cheers

**Comment by SimonBrazell** [comment] 2020-04-30 23:41
Hi @wuniversales I just had a look at the site you listed, it appears the issue is not with this extension but with the site itself using mixed content which is being blocked by the browser.

![Screen Shot 2020-05-01 at 9 38 44 am](https://user-images.githubusercontent.com/16571951/80769135-997e5900-8b8f-11ea-9a49-d8f7c0caf0de.png)

I tested this with both Firefox and Chromium with the same result.

Here is some further reading - https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Comment by wuniversales** [comment] 2020-05-01 01:12
But with the plugin you can correct that, right?

Instead of redirecting from youtube, to the invidius instance, you could change the link directly from the website.

That is, apart from making redirects, change the links on the websites.

Detect if it is in an embled, in an object, in an href ... And change the link directly to avoid unnecessary redirection.

This could detect the link and automatically repair it by an https link from invidius.

**Comment by SimonBrazell** [comment] 2020-05-01 01:23
In this case it seems the browser intervenes and blocks the content before the extension has a chance to perform the redirect so I'm not sure there is much that can be done other than contacting the site maintainer and asking them to fix the mixed content on their site.

The extension does not edit site content, it just intercepts requests made to the target URLs and redirects them to the desired ones, the browser blocking mixed content is interfering with this process in this case. Embedded video redirects work elsewhere as expected, the fault here lies with the specific site / page you trying to load.

**Comment by SimonBrazell** [comment] 2020-05-01 01:26
Or you could unblock the mixed content in your browser - https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox then the redirects should work but this is not recommended.

**Comment by SimonBrazell** [comment] 2020-05-01 03:08
Going to close this as it seems to be unrelated to the extension.

Let me know if you still have questions though.

**Closed by SimonBrazell** 2020-05-01 03:08 UTC
