### ISSUE TITLE
Don't Redirect "View on ..." links

### ISSUE THREAD

**Issue by matteqa** [SimonBrazell/privacy-redirect#30] opened 2020-03-29 10:35 UTC
When you click a View on YouTube link in Invidious it redirects back to invidious. It would be more useful if this actually went to YouTube as there is sometimes issues with some videos.

**Comment by SimonBrazell** [comment] 2020-03-29 22:58
Hi @matteqa, yes I agree, this should work, I'll include this in the next build.

To fix this I can compare the initiator URL to the list of instances on the invidious repo and not redirect from these. But that means it won't work for any private or unlisted instances but I'm not sure how many of those there are anyway.

**Comment by ToughGuyKunio** [comment] 2020-03-30 08:12
Wouldn't it be possible to compare the initiator URL to the instance variable set by the user to get private instances working?

**Comment by SimonBrazell** [comment] 2020-03-30 08:35
@ToughGuyKunio yes that's a much better idea, I'll do that instead. 

Thanks for the coffees btw mate, very much appreciated.

**Comment by SimonBrazell** [comment] 2020-03-31 04:14
Please let me know if there are any problems with redirects in the [latest version](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.18), this applies to Invidious, Nitter, and Bibliogram (OSM doesn't seem to have a similar feature). 

Not released on Chrome yet as the previous release still hasn't been approved...

**Comment by ToughGuyKunio** [comment] 2020-03-31 05:41
No view on youtube/twitter/instagram links work for me. Tested on both custom and standard instances.

**Comment by matteqa** [comment] 2020-03-31 05:45
Same issue here, tried on Firefox 74 with v1.1.18 but didn't work for Invidious or Bibliogram (not sure what links to test on Nitter). Even with the custom variables set in the settings for the servers.

Servers tested:

invidio.us
invidious.snopyta.org
bibliogram.pussthecat.org

**Comment by SimonBrazell** [comment] 2020-03-31 05:45
Hmm seems the behaviour is different on each browser... sorry I'll look into it.

**Comment by matteqa** [comment] 2020-03-31 05:46
Also tried installing the ZIP in Brave but that gave an error (I assume because it's the Firefox build)

**Comment by SimonBrazell** [comment] 2020-03-31 05:51
No problem I think I've found the issue, seems Firefox doesn't have the initiator value, funny I thought it would be compatible with Chrome, I'll find the alternative and fix this up with a new build.

@matteqa I haven't tested the plugin on Brave, in theory it should work but will need a CRX file to load, you can unzip the FF archive and then `Load unpacked` when in `Developer mode`.

**Comment by matteqa** [comment] 2020-03-31 05:55
I unpacked the ZIP in the releases and added it in Developer mode but got this error: 

Unrecognized manifest key 'browser_specific_settings'.

"browser_specific_settings": {
    "gecko": {
      "id": "{b7f9d2cd-d772-4302-8c3f-eb941af36f76}"
    }
  }

**Comment by matteqa** [comment] 2020-03-31 05:58
Removing that line from the manifest.json made it install but the redirects are still broken.

**Comment by SimonBrazell** [comment] 2020-03-31 05:59
@matteqa that should just be a warning, I get the same error on stock chrome but it still installs:

![Screen Shot 2020-03-31 at 4 57 59 pm](https://user-images.githubusercontent.com/16571951/77991955-ceb94080-7370-11ea-8e5f-9495ba357950.png)

See how it's a yellow warning symbol vs the red error. If that isn't the case then perhaps Brave handles extensions a little differently to Chromium.

**Comment by matteqa** [comment] 2020-03-31 06:01
For me it still was labelled as 1.1.16 in the extension until i removed the line. Odd that Brave handles it differently considering it's supposed to be standard Chromium underneath.

**Comment by ToughGuyKunio** [comment] 2020-03-31 06:15
I've been using the build from Chrome Store in Brave for a good while and had no problems with it.

**Comment by SimonBrazell** [comment] 2020-03-31 06:19
Must just be when trying to load unpacked extensions then, good to know.

I'm having issues with the Nitter 'View in Twitter' links, caused by another fix I added the other day that removes the Twitter service worker if present, it doesn't have access to the initiator like the background script does... Maybe I'll just push out the change for Invidious and Bibliogram for now?

**Comment by matteqa** [comment] 2020-03-31 06:21
The Chrome store version is working for me fine. Just had trouble installing this new version manually because Brave seems to handle warnings as errors. 

Also it turns out the reason the View As links weren't working for me on Brave was because I had two versions of the extension installed. My fault.

**Comment by SimonBrazell** [comment] 2020-03-31 06:22
Oh cool, yeah it was working on Chromium for me, and I'm getting it working on Firefox now, I'll push up a new build shortly. 

Thanks for your help!

**Comment by SimonBrazell** [comment] 2020-03-31 06:28
One other problem I've found with the way it's different on Firefox - if you click the watch on YouTube link, and then refresh that page on Chrome it redirects the page to Invidious like it should, but on Firefox it stays on Youtube... not sure if that will be a problem.

**Comment by SimonBrazell** [comment] 2020-03-31 06:29
Seems to work as expected if I copy the url to another tab though so at least the normal use cases aren't broken, so I think we are good to go, minus the Nitter links which I still need to work out.

**Comment by matteqa** [comment] 2020-03-31 06:30
Either way could be seen as expected behavior so i wouldnt worry about it

**Comment by SimonBrazell** [comment] 2020-03-31 06:42
Okay should be fixed now for Firefox in v1.1.19.

I've aborted the change for Nitter for now due to that other conflict I mentioned above.

**Comment by SimonBrazell** [comment] 2020-03-31 06:58
Let me know how you go.

@matteqa another Aussie 🦘👋

**Comment by matteqa** [comment] 2020-03-31 07:19
:wave:

**Comment by matteqa** [comment] 2020-03-31 07:20
Looks all good on my end!

Thanks for developing this extension btw, it's really useful.

**Comment by SimonBrazell** [comment] 2020-03-31 07:25
Awesome, I'll see if I can fix up the Nitter links in a future release! 

No worries, it's a bit fun building and maintaining it, keeps me busy, especially lately when I'm stuck at home day and night!

**Comment by ToughGuyKunio** [comment] 2020-03-31 09:09
Works for me too :+1:

**Comment by SimonBrazell** [comment] 2020-03-31 23:30
Thanks guys.

**Comment by DJCrashdummy** [comment] 2020-05-12 13:56
the *"open in twitter"*-links on nitter are still redirected (at least in firefox)... is still being worked on this (then wouldn't it be better to reopen & perhaps rename this issue) or won't this be fixed?
or should a new issue be opened about this particular issue?

**Comment by SimonBrazell** [comment] 2020-05-13 01:01
@DJCrashdummy yes you're right, this slipped my mind to be honest, I'll re-open this to help remind me in the future when I have more time to work on this project again.

**Comment by SimonBrazell** [comment] 2020-06-03 12:07
Should be completed now with '_open in twitter_' now working as expected  in v1.1.32, due to go live on AMO shortly.

**Closed by SimonBrazell** 2020-06-03 12:07 UTC
Labels: enhancement
